/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CcvRouteImport } from './routes/ccv'
import { Route as CifraRouteImport } from './routes/cifra'
import { Route as TriRouteImport } from './routes/tri'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CcvRoute = CcvRouteImport.update({
  id: '/ccv',
  path: '/ccv',
  getParentRoute: () => rootRouteImport,
} as any)
const CifraRoute = CifraRouteImport.update({
  id: '/cifra',
  path: '/cifra',
  getParentRoute: () => rootRouteImport,
} as any)
const TriRoute = TriRouteImport.update({
  id: '/tri',
  path: '/tri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ccv': typeof CcvRoute
  '/cifra': typeof CifraRoute
  '/tri': typeof TriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ccv': typeof CcvRoute
  '/cifra': typeof CifraRoute
  '/tri': typeof TriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ccv': typeof CcvRoute
  '/cifra': typeof CifraRoute
  '/tri': typeof TriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ccv' | '/cifra' | '/tri'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ccv' | '/cifra' | '/tri'
  id: '__root__' | '/' | '/ccv' | '/cifra' | '/tri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CcvRoute: typeof CcvRoute
  CifraRoute: typeof CifraRoute
  TriRoute: typeof TriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ccv': {
      id: '/ccv'
      path: '/ccv'
      fullPath: '/ccv'
      preLoaderRoute: typeof CcvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cifra': {
      id: '/cifra'
      path: '/cifra'
      fullPath: '/cifra'
      preLoaderRoute: typeof CifraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri': {
      id: '/tri'
      path: '/tri'
      fullPath: '/tri'
      preLoaderRoute: typeof TriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CcvRoute: CcvRoute,
  CifraRoute: CifraRoute,
  TriRoute: TriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
